# Generated by Django 4.2 on 2023-07-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
    ]
