# Generated by Django 4.2.3 on 2023-07-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255, unique=True)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='DowARtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255, unique=True)),
                ('artist_url', models.CharField(max_length=255)),
                ('artist_img_url', models.CharField(max_length=255)),
                ('style', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dow',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('music_ID', models.CharField(max_length=255, unique=True)),
                ('album', models.CharField(default='null', max_length=255)),
                ('label', models.CharField(default='null', max_length=255)),
                ('artist_url', models.CharField(default='null', max_length=255)),
                ('sources', models.CharField(default='loaction', max_length=255)),
                ('download_status', models.BooleanField(default=False)),
                ('style', models.CharField(default='null', max_length=255)),
                ('country', models.CharField(default='null', max_length=255)),
                ('language', models.CharField(default='null', max_length=255)),
                ('description', models.CharField(default='null', max_length=255)),
                ('keywords', models.CharField(default='null', max_length=255)),
                ('ch_lyrics', models.TextField(default='null')),
                ('en_lyrics', models.TextField(default='null')),
                ('rating', models.CharField(default='null', max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('release_year', models.IntegerField(default=0)),
                ('publish_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('music_ID', models.CharField(max_length=255)),
                ('album', models.CharField(default='null', max_length=255)),
                ('label', models.CharField(default='null', max_length=255)),
                ('artist_url', models.CharField(default='null', max_length=255)),
                ('sources', models.CharField(default='loaction', max_length=255)),
                ('download_status', models.BooleanField(default=False)),
                ('style', models.CharField(default='null', max_length=255)),
                ('country', models.CharField(default='null', max_length=255)),
                ('language', models.CharField(default='null', max_length=255)),
                ('description', models.CharField(default='null', max_length=255)),
                ('keywords', models.CharField(default='null', max_length=255)),
                ('ch_lyrics', models.TextField(default='null')),
                ('en_lyrics', models.TextField(default='null')),
                ('rating', models.CharField(default='null', max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('release_year', models.IntegerField(default=0)),
                ('publish_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'style',
            },
        ),
        migrations.CreateModel(
            name='StyleTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('style', models.CharField(default='null', max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'styleTitle',
            },
        ),
    ]
