# Generated by Django 4.2.3 on 2023-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('music_ID', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'failSong',
            },
        ),
    ]
