# Generated by Django 4.2.3 on 2023-07-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
