# Generated by Django 4.2.3 on 2023-08-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_failsong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failsong',
            name='title',
        ),
    ]
