# Generated by Django 4.2.3 on 2023-09-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_remove_failsong_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='summary',
            field=models.TextField(default='summary'),
        ),
    ]
