# Generated by Django 4.2.3 on 2023-09-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usererrorlog',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
