# Generated by Django 4.2.3 on 2023-09-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_delete_level'),
        ('Reviews', '0002_rename_date_created_comment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('comment', 'Comment'), ('error', 'Error')], max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='usererrorlog',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='UserErrorLog',
        ),
    ]
