# Generated by Django 4.2.3 on 2023-08-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('proj', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'library',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('principal', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('opcode', models.CharField(max_length=255)),
                ('source', models.CharField(default='server', max_length=255)),
                ('code', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'taskLog',
            },
        ),
    ]
