# Generated by Django 4.2.3 on 2023-08-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='DiscoverSong',
        ),
    ]
