# Generated by Django 4.2.3 on 2023-08-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discover', '0002_discovertitle_delete_discoversong'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='discovertitle',
            table='discoverTitle',
        ),
    ]
