# Generated by Django 4.2.3 on 2023-07-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=24)),
                ("username", models.CharField(max_length=24)),
                ("phone", models.CharField(max_length=16)),
                ("country", models.CharField(max_length=2, null=True)),
                ("birthday", models.DateField(null=True)),
                ("gender", models.CharField(max_length=1, null=True)),
                ("user_img_url", models.CharField(max_length=255, null=True)),
                ("test", models.PositiveSmallIntegerField(default=0)),
                ("level", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "UID_SETTING",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("LANGUAGE", models.CharField(max_length=255)),
                ("SHOW_MODAL", models.CharField(max_length=255)),
                ("AUDIO_QUALITY", models.CharField(max_length=255)),
                ("AUDIO_AUTO_PLAY", models.BooleanField()),
                ("WIFI_AUTO_DOWNLOAD", models.BooleanField()),
                ("CREATED_AT", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_setting",
            },
        ),
        migrations.CreateModel(
            name="UserSettingEQ",
            fields=[
                (
                    "UID_EQ",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("ENGANCE_HIGH", models.BooleanField(blank=True, null=True)),
                ("ENGANCE_MIDDLE", models.BooleanField(blank=True, null=True)),
                ("ENGANCE_LOW", models.BooleanField(blank=True, null=True)),
                ("ENGANCE_HEAVY", models.BooleanField(blank=True, null=True)),
                ("STYLE", models.CharField(blank=True, max_length=255, null=True)),
                ("EQ_HIGH", models.IntegerField(null=True)),
                ("EQ_MIDDLE", models.IntegerField(null=True)),
                ("EQ_LOW", models.IntegerField(null=True)),
                ("EQ_HEAVY", models.IntegerField(null=True)),
                ("EQ_DISTORTION", models.IntegerField(null=True)),
                ("EQ_ZIP", models.IntegerField(null=True)),
                (
                    "SPATIAL_AUDIO",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "user_setting_eq",
            },
        ),
        migrations.CreateModel(
            name="UserSocial",
            fields=[
                (
                    "userid",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=24)),
                ("uid", models.CharField(max_length=24)),
            ],
            options={
                "db_table": "user_social",
            },
        ),
    ]
