# Generated by Django 4.2.3 on 2023-07-30 15:49

import User.models
import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.IntegerField()),
                ('song', models.IntegerField()),
                ('style', models.IntegerField()),
                ('dow', models.IntegerField()),
                ('user', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adminCount',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='EQ',
            fields=[
                ('uid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('ENGANCE_HIGH', models.BooleanField(blank=True, default=False, null=True)),
                ('ENGANCE_MIDDLE', models.BooleanField(blank=True, default=False, null=True)),
                ('ENGANCE_LOW', models.BooleanField(blank=True, default=False, null=True)),
                ('ENGANCE_HEAVY', models.BooleanField(blank=True, default=False, null=True)),
                ('STYLE', models.CharField(blank=True, default='auto', max_length=255, null=True)),
                ('EQ_HIGH', models.IntegerField(default=0, null=True)),
                ('EQ_MIDDLE', models.IntegerField(default=0, null=True)),
                ('EQ_LOW', models.IntegerField(default=0, null=True)),
                ('EQ_HEAVY', models.IntegerField(default=0, null=True)),
                ('EQ_DISTORTION', models.IntegerField(default=0, null=True)),
                ('EQ_ZIP', models.IntegerField(default=0, null=True)),
                ('SPATIAL_AUDIO', models.CharField(blank=True, default='auto', max_length=255, null=True)),
                ('_60HZ', models.IntegerField(default=0, null=True)),
                ('_230HZ', models.IntegerField(default=0, null=True)),
                ('_910HZ', models.IntegerField(default=0, null=True)),
                ('_4kHZ', models.IntegerField(default=0, null=True)),
                ('_14kHZ', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=User.models.custom_default_date)),
            ],
            options={
                'db_table': 'eq',
            },
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_ID', models.CharField(max_length=200, unique=True)),
                ('count', models.IntegerField(null=True)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'listeningHistory',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='null', max_length=36)),
                ('playlist', models.CharField(max_length=255)),
                ('music_ID', models.CharField(max_length=32)),
                ('favorite', models.PositiveSmallIntegerField(default=0)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=User.models.custom_default_date)),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(default=None, max_length=24, null=True)),
                ('username', models.CharField(max_length=24)),
                ('phone', models.CharField(default=0, max_length=16)),
                ('country', models.CharField(default=None, max_length=2, null=True)),
                ('birthday', models.DateField(default=datetime.datetime.now, null=True)),
                ('gender', models.CharField(default='K', max_length=1, null=True)),
                ('level', models.PositiveSmallIntegerField(default=0, null=True)),
                ('invitation_code', models.CharField(default=uuid.uuid4, editable=False, max_length=255)),
                ('invited_by_code', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=User.models.custom_default_date)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=36)),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'searchHistory',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('uid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('LANGUAGE', models.CharField(default='ch', max_length=255)),
                ('SHOW_MODAL', models.CharField(default='auto', max_length=255)),
                ('AUDIO_QUALITY', models.CharField(default='auto', max_length=255)),
                ('AUDIO_AUTO_PLAY', models.BooleanField(default=True)),
                ('WIFI_AUTO_DOWNLOAD', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=User.models.custom_default_date)),
            ],
            options={
                'db_table': 'setting',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=24)),
                ('uid', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(default=User.models.custom_default_date)),
            ],
            options={
                'db_table': 'social',
            },
        ),
    ]
