# Generated by Django 4.2.3 on 2023-07-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
