# Generated by Django 4.2.3 on 2023-08-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invited_by_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
