# Generated by Django 4.2.3 on 2023-07-22 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="UserSetting",
        ),
        migrations.DeleteModel(
            name="UserSettingEQ",
        ),
        migrations.DeleteModel(
            name="UserSocial",
        ),
    ]
