# Generated by Django 4.2.3 on 2023-07-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_playlist_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=36)),
                ('music_ID', models.CharField(max_length=200)),
                ('count', models.IntegerField(null=True)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'listeningHistory',
            },
        ),
        migrations.AlterField(
            model_name='social',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
