# Generated by Django 4.2.3 on 2023-08-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_profile_invited_by_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='uid',
            field=models.CharField(default=True, max_length=36, unique=True),
        ),
    ]
