# Generated by Django 4.2.3 on 2023-07-26 14:26

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EQ',
            fields=[
                ('UID_EQ', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('ENGANCE_HIGH', models.BooleanField(blank=True, null=True)),
                ('ENGANCE_MIDDLE', models.BooleanField(blank=True, null=True)),
                ('ENGANCE_LOW', models.BooleanField(blank=True, null=True)),
                ('ENGANCE_HEAVY', models.BooleanField(blank=True, null=True)),
                ('STYLE', models.CharField(blank=True, max_length=255, null=True)),
                ('EQ_HIGH', models.IntegerField(null=True)),
                ('EQ_MIDDLE', models.IntegerField(null=True)),
                ('EQ_LOW', models.IntegerField(null=True)),
                ('EQ_HEAVY', models.IntegerField(null=True)),
                ('EQ_DISTORTION', models.IntegerField(null=True)),
                ('EQ_ZIP', models.IntegerField(null=True)),
                ('SPATIAL_AUDIO', models.CharField(blank=True, max_length=255, null=True)),
                ('_60HZ', models.IntegerField(null=True)),
                ('_230HZ', models.IntegerField(null=True)),
                ('_910HZ', models.IntegerField(null=True)),
                ('_4kHZ', models.IntegerField(null=True)),
                ('_14kHZ', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=User.models.custom_default_date)),
            ],
            options={
                'db_table': 'eq',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=24)),
                ('username', models.CharField(max_length=24)),
                ('phone', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=2, null=True)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('user_img_url', models.CharField(max_length=255, null=True)),
                ('test', models.PositiveSmallIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=User.models.custom_default_date)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('UID_SETTING', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('LANGUAGE', models.CharField(max_length=255)),
                ('SHOW_MODAL', models.CharField(max_length=255)),
                ('AUDIO_QUALITY', models.CharField(max_length=255)),
                ('AUDIO_AUTO_PLAY', models.BooleanField()),
                ('WIFI_AUTO_DOWNLOAD', models.BooleanField()),
                ('created_at', models.DateTimeField(default=User.models.custom_default_date)),
            ],
            options={
                'db_table': 'setting',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('userid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=24)),
                ('uid', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(default=User.models.custom_default_date)),
            ],
            options={
                'db_table': 'social',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserSetting',
        ),
        migrations.DeleteModel(
            name='UserSettingEQ',
        ),
        migrations.DeleteModel(
            name='UserSocial',
        ),
        migrations.RemoveField(
            model_name='usermusiclist',
            name='create_at',
        ),
        migrations.AddField(
            model_name='usermusiclist',
            name='created_at',
            field=models.DateTimeField(default=User.models.custom_default_date),
        ),
    ]
