# Generated by Django 4.2.3 on 2023-07-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_listeninghistory_alter_social_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeninghistory',
            name='uid',
        ),
    ]
