# Generated by Django 4.2.3 on 2023-08-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_contract_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeninghistory',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
