# Generated by Django 4.2.3 on 2023-07-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_listeninghistory_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeninghistory',
            name='music_ID',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
