# Generated by Django 4.2.3 on 2023-07-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_eq_profile_setting_social_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMusicList',
            new_name='musicList',
        ),
        migrations.RenameField(
            model_name='eq',
            old_name='UID_EQ',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='UID_SETTING',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='userid',
            new_name='id',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.eq')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.setting')),
            ],
        ),
    ]
