# Generated by Django 4.2.3 on 2023-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_listeninghistory_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUsersong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=True, max_length=36, unique=True)),
                ('artist', models.CharField(max_length=100)),
                ('music_ID', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lastUsersong',
            },
        ),
    ]
