# Generated by Django 4.2.3 on 2023-07-28 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_listeninghistory_music_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_img_url',
        ),
        migrations.AlterField(
            model_name='eq',
            name='ENGANCE_HEAVY',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='ENGANCE_HIGH',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='ENGANCE_LOW',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='ENGANCE_MIDDLE',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='EQ_DISTORTION',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='EQ_HEAVY',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='EQ_HIGH',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='EQ_LOW',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='EQ_MIDDLE',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='EQ_ZIP',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='SPATIAL_AUDIO',
            field=models.CharField(blank=True, default='auto', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='STYLE',
            field=models.CharField(blank=True, default='auto', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='_14kHZ',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='_230HZ',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='_4kHZ',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='_60HZ',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='_910HZ',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='K', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
