# Generated by Django 4.2.3 on 2023-07-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_rename_usermusiclist_musiclist_rename_uid_eq_eq_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
