# Generated by Django 4.2.3 on 2023-08-25 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_lastusersong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regName', models.CharField(max_length=100)),
                ('code', models.CharField(default=uuid.uuid4, max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
