# Generated by Django 4.2.3 on 2023-08-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eq',
            old_name='EQ_DISTORTION',
            new_name='_128HZ',
        ),
        migrations.RenameField(
            model_name='eq',
            old_name='EQ_HEAVY',
            new_name='_1kHZ',
        ),
        migrations.RenameField(
            model_name='eq',
            old_name='EQ_HIGH',
            new_name='_256HZ',
        ),
        migrations.RenameField(
            model_name='eq',
            old_name='EQ_LOW',
            new_name='_2kHZ',
        ),
        migrations.RenameField(
            model_name='eq',
            old_name='EQ_MIDDLE',
            new_name='_32HZ',
        ),
        migrations.RenameField(
            model_name='eq',
            old_name='EQ_ZIP',
            new_name='_512HZ',
        ),
        migrations.RenameField(
            model_name='eq',
            old_name='_14kHZ',
            new_name='_64HZ',
        ),
        migrations.RemoveField(
            model_name='eq',
            name='ENGANCE_HEAVY',
        ),
        migrations.RemoveField(
            model_name='eq',
            name='ENGANCE_HIGH',
        ),
        migrations.RemoveField(
            model_name='eq',
            name='ENGANCE_LOW',
        ),
        migrations.RemoveField(
            model_name='eq',
            name='ENGANCE_MIDDLE',
        ),
        migrations.RemoveField(
            model_name='eq',
            name='SPATIAL_AUDIO',
        ),
        migrations.RemoveField(
            model_name='eq',
            name='_230HZ',
        ),
        migrations.RemoveField(
            model_name='eq',
            name='_4kHZ',
        ),
        migrations.RemoveField(
            model_name='eq',
            name='_60HZ',
        ),
        migrations.RemoveField(
            model_name='eq',
            name='_910HZ',
        ),
    ]
