# Generated by Django 4.2.3 on 2023-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_profile_user_img_url_alter_eq_engance_heavy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.IntegerField()),
                ('song', models.IntegerField()),
                ('style', models.IntegerField()),
                ('dow', models.IntegerField()),
                ('user', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Count',
            },
        ),
    ]
