# Generated by Django 4.2.3 on 2023-09-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_eq_distortion_eq__128hz_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
