# Generated by Django 4.2.3 on 2023-07-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
    ]
