# Generated by Django 4.2.3 on 2023-07-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
