# Generated by Django 4.2.3 on 2023-09-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_delete_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
