# Generated by Django 4.2.3 on 2023-07-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='uid',
        ),
    ]
