# Generated by Django 4.2.3 on 2023-07-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_id_profile_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eq',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='id',
            new_name='uid',
        ),
    ]
