# Generated by Django 4.2.3 on 2023-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_rename_id_eq_uid_rename_id_setting_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default=None, max_length=24),
        ),
    ]
