# Generated by Django 4.2.3 on 2023-07-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
    ]
