# Generated by Django 4.2.3 on 2023-07-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='AUDIO_AUTO_PLAY',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='AUDIO_QUALITY',
            field=models.CharField(default='auto', max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='LANGUAGE',
            field=models.CharField(default='ch', max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='SHOW_MODAL',
            field=models.CharField(default='auto', max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='WIFI_AUTO_DOWNLOAD',
            field=models.BooleanField(default=False),
        ),
    ]
