# Generated by Django 4.2.3 on 2023-07-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_alter_setting_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq',
            name='uid',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
