# Generated by Django 4.2.3 on 2023-09-05 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tab',
            old_name='title',
            new_name='tab',
        ),
    ]
